rules:
- from:
    all: true
  to:
    networks:
    - LTE
  action:
    nat: MASQUERADE
    mangle: TTL --ttl-set 65
- from:
    networks:
    - MGMT
    - LAN
    - Security
  to:
    networks:
    - LTE
  action:
    filter: ACCEPT
