rules:
- from:
    all: true
  to:
    networks:
    - LTE
  action:
    nat: MASQUERADE
    mangle: SET-TTL 65
rules:
- from:
    networks:
    - MGMT
    - LAN
    - Security
  to:
    networks:
    - LTE
  action:
    filter: ACCEPT
