global:
  authority-config:
    soa-ttl: 24h
    ns-ttl: 24h
    nameservers:
    - ns-ip1.foxden.network
    - ns-ip2.foxden.network
    - ns-ip3.foxden.network
    - ns-ip4.foxden.network
    mailbox: ips.foxden.network
  listen:
  - ":53"
  prometheus-listen: :9001

rdns:
  - ip_version: 6
    address-ttl: 24h
    ptr-ttl: 24h
    suffix: ip6.foxden.network
    subnets:
      - 2a0e:7d44:f069::/48
      - 2a0e:7d44:f00a::/48
      - 2a0e:7d44:f00b::/48
