defaults:
  backends:
    http:
      host: 172.17.0.1
      port: 80
    https:
      host: 172.17.0.1
      port: 443
templates:
  host:
    http:
      host: 172.17.0.1
    https:
      host: 172.17.0.1
  router:
    http:
      host: 10.3.1.1
    https:
      host: 10.3.1.1
  router-backup:
    http:
      host: 10.3.1.2
    https:
      host: 10.3.1.2
  bengalfox:
    http:
      host: 10.2.11.1
      proxy_protocol: true
    https:
      host: 10.2.11.1
      proxy_protocol: true
  grafana:
    http:
      host: 10.2.11.5
      proxy_protocol: true
    https:
      host: 10.2.11.5
      proxy_protocol: true
  spaceage-web:
    http:
      host: 10.3.10.5
      proxy_protocol: true
      port: 8080
    https:
      host: 10.3.10.5
      proxy_protocol: true
      port: 8443
  foxcaves:
    http:
      host: 10.3.10.1
      proxy_protocol: true
      port: 8080
    https:
      host: 10.3.10.1
      proxy_protocol: true
      port: 8443
  git:
    http:
      host: 10.3.10.2
      proxy_protocol: true
    https:
      host: 10.3.10.2
      proxy_protocol: true
  hashtopolis:
    http:
      host: 10.2.11.17
      proxy_protocol: true
    https:
      host: 10.2.11.17
      proxy_protocol: true
  homeassistant:
    http:
      host: 10.2.12.2
      #proxy_protocol: true
      #port: 8080
    https:
      host: 10.2.12.2
      #proxy_protocol: true
      #port: 8443
  spaceage-website:
    http:
      host: 10.3.10.9
    https:
      host: 10.3.10.9
  website:
    http:
      host: 10.3.10.10
    https:
      host: 10.3.10.10
  syncthing:
    http:
      host: 10.2.11.2
    https:
      host: 10.2.11.2
  bengalfox-syncthing:
    http:
      host: 10.2.11.15
    https:
      host: 10.2.11.15
  jellyfin:
    http:
      host: 10.2.11.18
    https:
      host: 10.2.11.18
  yiffws:
    http:
      host: 10.3.10.11
    https:
      host: 10.3.10.11
  foxmov:
    http:
      host: 10.3.10.12
    https:
      host: 10.3.10.12
hosts:
  # Home network
  grafana.foxden.network:
    template: grafana
  nas.foxden.network:
    template: bengalfox
  dav.foxden.network:
    template: bengalfox
  homeassistant.foxden.network:
    template: homeassistant
  syncthing.foxden.network:
    template: syncthing
  bengalfox-syncthing.foxden.network:
    template: bengalfox-syncthing
  htpl.foxden.network:
    template: hashtopolis
  jellyfin.foxden.network:
    template: jellyfin

  router.foxden.network:
    template: router
  router-backup.foxden.network:
    template: router-backup

  # SpaceAge
  api.spaceage.mp:
    template: spaceage-web
  tts.spaceage.mp:
    template: spaceage-web
  spaceage.mp:
    template: spaceage-website
  www.spaceage.mp:
    template: spaceage-website

  # foxCaves
  foxcav.es:
    template: foxcaves
  www.foxcav.es:
    template: foxcaves
  f0x.es:
    template: foxcaves
  www.f0x.es:
    template: foxcaves

  yiff.ws:
    template: yiffws
  www.yiff.ws:
    template: yiffws

  # Personal website
  doridian.de:
    template: website
  www.doridian.de:
    template: website
  doridian.net:
    template: website
  www.doridian.net:
    template: website

  git.foxden.network:
    template: git
