global:
  authority-config:
    nameservers:
    - ns1.foxden.network
    - ns2.foxden.network
    - ns3.foxden.network
    - ns4.foxden.network
    serial: 2024042069
    refresh: 2h
    retry: 30m
    expire: 336h
    minttl: 1h
    mailbox: dns.foxden.network
  listen:
  - ":53"
  prometheus-listen: :9001

rdns:
  - ip_version: 6
    suffix: ip6.foxden.network
    subnets:
      - 2a0e:7d44:f069::/48
      - 2a0e:7d44:f00a::/48
      - 2a0e:7d44:f00b::/48
  - ip_version: 4
    suffix: ip4.foxden.network
    subnets:
      - 192.168.0.0/16
      - 172.16.0.0/12


static-zones:
  - zone: foxden.network
    file: foxden.network.txt
    resolve-external-cnames: true
    authority-config:
      zone-name: foxden.network
      dnssec-private-ksk: Kfoxden.network.+013+56289.private
      dnssec-public-ksk: Kfoxden.network.+013+56289.key
      dnssec-private-zsk: Kfoxden.network.+013+12422.private
      dnssec-public-zsk: Kfoxden.network.+013+12422.key
      dnssec-cache-signatures: true
  - zone: 10.in-addr.arpa
    file: 10.in-addr.arpa.txt

  - zone: doridian.net
    file: doridian.net.db
    resolve-external-cnames: true
  - zone: foxcav.es
    file: foxcav.es.db
    resolve-external-cnames: true
  - zone: f0x.es
    file: f0x.es.db
    resolve-external-cnames: true
  - zone: spaceage.mp
    file: spaceage.mp.db
    resolve-external-cnames: true

  - zone: wpad
    file: empty.db
  - zone: local
    file: empty.db

  - zone: 254.169.in-addr.arpa
    file: empty.db
  - zone: 127.in-addr.arpa
    file: empty.db
  - zone: 0.0.0.0.in-addr.arpa
    file: empty.db
  - zone: 255.255.255.255.in-addr.arpa
    file: empty.db
  - zone: 224.in-addr.arpa
    file: empty.db
  - zone: 225.in-addr.arpa
    file: empty.db
  - zone: 226.in-addr.arpa
    file: empty.db
  - zone: 227.in-addr.arpa
    file: empty.db
  - zone: 228.in-addr.arpa
    file: empty.db
  - zone: 229.in-addr.arpa
    file: empty.db
  - zone: 230.in-addr.arpa
    file: empty.db
  - zone: 231.in-addr.arpa
    file: empty.db
  - zone: 232.in-addr.arpa
    file: empty.db
  - zone: 233.in-addr.arpa
    file: empty.db
  - zone: 234.in-addr.arpa
    file: empty.db
  - zone: 235.in-addr.arpa
    file: empty.db
  - zone: 236.in-addr.arpa
    file: empty.db
  - zone: 237.in-addr.arpa
    file: empty.db
  - zone: 238.in-addr.arpa
    file: empty.db
  - zone: 239.in-addr.arpa
    file: empty.db

  - zone: 0.0.f.f.ip6.arpa
    file: empty.db
  - zone: 0.0.c.f.ip6.arpa
    file: empty.db
  - zone: 0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.e.f.ip6.arpa
    file: empty.db

  - zone: 8.8.8.8.in-addr.arpa
    file: dns-google-ptr.db
  - zone: 4.4.8.8.in-addr.arpa
    file: dns-google-ptr.db

  - zone: localhost
    file: localhost.db
  - zone: localdomain
    file: localhost.db

resolvers:
  - zone: .
    cache-size: 32768
    nameserver-strategy: failover
    nameservers:
      - proto: tcp
        addr: 192.152.0.1:53
        max-parallel-queries: 20
        timeout: 500ms
      - proto: tcp
        addr: 192.152.0.2:53
        max-parallel-queries: 20
        timeout: 500ms
    allow-only-from-private: true
    cache-min-time: 1m
    cache-max-time: 24h
    cache-no-reply-time: 1m
    record-min-ttl: 1m
    cache-stale-entry-keep-period: 15m
    cache-return-stale-period: 5m
    log-failures: true

localizers:
  - zone: gateway.foxden.network
    subnets:
    - 0.0.0.1/16
    rewrites:
    - from: 10.100.0.0/16
      to: 10.2.0.0
    authority-config:
      zone-name: foxden.network
      dnssec-private-ksk: Kfoxden.network.+013+56289.private
      dnssec-public-ksk: Kfoxden.network.+013+56289.key
      dnssec-private-zsk: Kfoxden.network.+013+12422.private
      dnssec-public-zsk: Kfoxden.network.+013+12422.key
      dnssec-cache-signatures: true
  - zone: dns.foxden.network
    subnets:
    - 0.0.0.53/16
    rewrites:
    - from: 10.100.0.0/16
      to: 10.2.0.0
    authority-config:
      zone-name: foxden.network
      dnssec-private-ksk: Kfoxden.network.+013+56289.private
      dnssec-public-ksk: Kfoxden.network.+013+56289.key
      dnssec-private-zsk: Kfoxden.network.+013+12422.private
      dnssec-public-zsk: Kfoxden.network.+013+12422.key
      dnssec-cache-signatures: true
  - zone: ntp.foxden.network
    subnets:
    - 0.0.0.123/16
    rewrites:
    - from: 10.100.0.0/16
      to: 10.2.0.0
    authority-config:
      zone-name: foxden.network
      dnssec-private-ksk: Kfoxden.network.+013+56289.private
      dnssec-public-ksk: Kfoxden.network.+013+56289.key
      dnssec-private-zsk: Kfoxden.network.+013+12422.private
      dnssec-public-zsk: Kfoxden.network.+013+12422.key
      dnssec-cache-signatures: true
  - zone: vpn.foxden.network
    subnets:
    - 0.0.1.1/16
    rewrites:
    - from: 10.100.0.0/16
      to: 10.2.0.0
    authority-config:
      zone-name: foxden.network
      dnssec-private-ksk: Kfoxden.network.+013+56289.private
      dnssec-public-ksk: Kfoxden.network.+013+56289.key
      dnssec-private-zsk: Kfoxden.network.+013+12422.private
      dnssec-public-zsk: Kfoxden.network.+013+12422.key
      dnssec-cache-signatures: true
  - zone: router.foxden.network
    subnets:
    - 0.0.1.1/16
    rewrites:
    - from: 10.100.0.0/16
      to: 10.2.0.0
    authority-config:
      zone-name: foxden.network
      dnssec-private-ksk: Kfoxden.network.+013+56289.private
      dnssec-public-ksk: Kfoxden.network.+013+56289.key
      dnssec-private-zsk: Kfoxden.network.+013+12422.private
      dnssec-public-zsk: Kfoxden.network.+013+12422.key
      dnssec-cache-signatures: true
  - zone: ntpi.foxden.network
    subnets:
    - 0.0.1.123/16
    rewrites:
    - from: 10.100.0.0/16
      to: 10.2.0.0
    authority-config:
      zone-name: foxden.network
      dnssec-private-ksk: Kfoxden.network.+013+56289.private
      dnssec-public-ksk: Kfoxden.network.+013+56289.key
      dnssec-private-zsk: Kfoxden.network.+013+12422.private
      dnssec-public-zsk: Kfoxden.network.+013+12422.key
      dnssec-cache-signatures: true
  - zone: router-backup.foxden.network
    subnets:
    - 0.0.1.2/16
    rewrites:
    - from: 10.100.0.0/16
      to: 10.2.0.0
    authority-config:
      zone-name: foxden.network
      dnssec-private-ksk: Kfoxden.network.+013+56289.private
      dnssec-public-ksk: Kfoxden.network.+013+56289.key
      dnssec-private-zsk: Kfoxden.network.+013+12422.private
      dnssec-public-zsk: Kfoxden.network.+013+12422.key
      dnssec-cache-signatures: true
