global:
  authority-config:
    nameservers:
    - ns1.foxden.network
    - ns2.foxden.network
    - ns3.foxden.network
    - ns4.foxden.network
    mailbox: dns.foxden.network
  listen:
  - ":53"
  prometheus-listen: :9001

rdns:
  - ip_version: 6
    suffix: ip6.foxden.network
    subnets:
      - 2001:470:b:39::/64
      - 2001:470:e820::/48
      - 2001:470:b:3c9::/64
      - 2001:470:e963::/48
      - 2a0e:7d44:f069::/48
      - 2a0e:7d44:f00a::/48
      - 2a0e:7d44:f00b::/48
  - ip_version: 4
    suffix: ip4.foxden.network
    subnets:
      - 192.168.0.0/16
      - 172.16.0.0/12


static-zones:
  foxden.network: foxden.network.txt
  10.in-addr.arpa: 10.in-addr.arpa.txt

  doridian.net: doridian.net.db
  foxcav.es: foxcav.es.db
  f0x.es: f0x.es.db
  yiff.ws: yiff.ws.db

  wpad: empty.db
  local: empty.db

  254.169.in-addr.arpa: empty.db
  127.in-addr.arpa: empty.db
  0.0.0.0.in-addr.arpa: empty.db
  255.255.255.255.in-addr.arpa: empty.db
  224.in-addr.arpa: empty.db
  225.in-addr.arpa: empty.db
  226.in-addr.arpa: empty.db
  227.in-addr.arpa: empty.db
  228.in-addr.arpa: empty.db
  229.in-addr.arpa: empty.db
  230.in-addr.arpa: empty.db
  231.in-addr.arpa: empty.db
  232.in-addr.arpa: empty.db
  233.in-addr.arpa: empty.db
  234.in-addr.arpa: empty.db
  235.in-addr.arpa: empty.db
  236.in-addr.arpa: empty.db
  237.in-addr.arpa: empty.db
  238.in-addr.arpa: empty.db
  239.in-addr.arpa: empty.db
  0.0.f.f.ip6.arpa: empty.db
  0.0.c.f.ip6.arpa: empty.db
  0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.e.f.ip6.arpa: empty.db

  8.8.8.8.in-addr.arpa: dns-google-ptr.db
  4.4.8.8.in-addr.arpa: dns-google-ptr.db

  archive.ubuntu.com: apt-mirror.ubuntu.db
  ports.ubuntu.com: apt-mirror.ubuntu.db
  security.ubuntu.com: apt-mirror.ubuntu.db
  ftp.debian.org: apt-mirror.db
  deb.debian.org: apt-mirror.db
  ftp.us.debian.org: apt-mirror.db
  deb.us.debian.org: apt-mirror.db

  localhost: localhost.db
  localdomain: localhost.db

resolvers:
  - zone: .
    max-connections: 20
    cache-size: 32768
    nameservers:
      - proto: tcp-tls
        server-name: dns.google
        addr: "8.8.8.8:853"
      - proto: tcp-tls
        server-name: dns.google
        addr: "8.8.4.4:853"
    allow-only-from-private: true
    cache-min-time: 1m
    cache-max-time: 24h
    cache-no-reply-time: 1m
    record-min-ttl: 1m
    cache-stale-entry-keep-period: 15m
    cache-return-stale-period: 5m
    log-failures: true

localizers:
  - zone: gateway.foxden.network
    subnets:
    - 0.0.0.1/16
  - zone: dns.foxden.network
    subnets:
    - 0.0.0.53/16
  - zone: ntp.foxden.network
    subnets:
    - 0.0.0.123/16
  - zone: vpn.foxden.network
    subnets:
    - 0.0.1.1/16
  - zone: router.foxden.network
    subnets:
    - 0.0.1.1/16
  - zone: ntpi.foxden.network
    subnets:
    - 0.0.1.2/16
  - zone: router-backup.foxden.network
    subnets:
    - 0.0.1.3/16
