global:
  nameservers:
  - ns1.foxden.network
  - ns2.foxden.network
  - ns3.foxden.network
  - ns4.foxden.network
  mailbox: dns.foxden.network
  listen:
  - ":53"

rdns:
  - ip_version: 6
    suffix: ip6.foxden.network
    subnets:
      - 3.6.9.e.0.7.4.0.1.0.0.2.ip6.arpa
      - 0.2.8.e.0.7.4.0.1.0.0.2.ip6.arpa
      - 9.3.0.0.b.0.0.0.0.7.4.0.1.0.0.2.ip6.arpa
      - 9.c.3.0.b.0.0.0.0.7.4.0.1.0.0.2.ip6.arpa

resolvers:
  - zone: .
    nameservers: ["8.8.8.8:53", "8.8.4.4:53"]

localizers:
  gateway.foxden.test:
  - 0.0.0.1/16
  dns.foxden.test:
  - 0.0.0.53/16
  ntp.foxden.test:
  - 0.0.0.123/16
  gateway.foxden.network:
  - 0.0.0.1/16
  dns.foxden.network:
  - 0.0.0.53/16
  ntp.foxden.network:
  - 0.0.0.123/16
