global:
  authority-config:
    nameservers:
    - ns1.foxden.network
    - ns2.foxden.network
    - ns3.foxden.network
    - ns4.foxden.network
    mailbox: dns.foxden.network
  listen:
  - ":53"
  prometheus-listen: :9001

rdns:
  - ip_version: 6
    suffix: ip6.foxden.network
    subnets:
      - 3.6.9.e.0.7.4.0.1.0.0.2.ip6.arpa
      - 0.2.8.e.0.7.4.0.1.0.0.2.ip6.arpa
      - 9.3.0.0.b.0.0.0.0.7.4.0.1.0.0.2.ip6.arpa
      - 9.c.3.0.b.0.0.0.0.7.4.0.1.0.0.2.ip6.arpa
      - 9.6.0.f.4.4.d.7.e.0.a.2.ip6.arpa
  - ip_version: 4
    suffix: ip4.foxden.network
    subnets:
      - 168.192.in-addr.arpa
      - 16.172.in-addr.arpa
      - 17.172.in-addr.arpa
      - 18.172.in-addr.arpa
      - 19.172.in-addr.arpa
      - 20.172.in-addr.arpa
      - 21.172.in-addr.arpa
      - 22.172.in-addr.arpa
      - 23.172.in-addr.arpa
      - 24.172.in-addr.arpa
      - 25.172.in-addr.arpa
      - 26.172.in-addr.arpa
      - 27.172.in-addr.arpa
      - 28.172.in-addr.arpa
      - 29.172.in-addr.arpa
      - 30.172.in-addr.arpa
      - 31.172.in-addr.arpa


static-zones:
  foxden.network: foxden.network.txt
  10.in-addr.arpa: 10.in-addr.arpa.txt

  doridian.net: doridian.net.db
  foxcav.es: foxcav.es.db
  f0x.es: f0x.es.db

  wpad: empty.db
  local: empty.db

  254.169.in-addr.arpa: empty.db
  127.in-addr.arpa: empty.db
  0.0.0.0.in-addr.arpa: empty.db
  255.255.255.255.in-addr.arpa: empty.db
  224.in-addr.arpa: empty.db
  225.in-addr.arpa: empty.db
  226.in-addr.arpa: empty.db
  227.in-addr.arpa: empty.db
  228.in-addr.arpa: empty.db
  229.in-addr.arpa: empty.db
  230.in-addr.arpa: empty.db
  231.in-addr.arpa: empty.db
  232.in-addr.arpa: empty.db
  233.in-addr.arpa: empty.db
  234.in-addr.arpa: empty.db
  235.in-addr.arpa: empty.db
  236.in-addr.arpa: empty.db
  237.in-addr.arpa: empty.db
  238.in-addr.arpa: empty.db
  239.in-addr.arpa: empty.db
  0.0.f.f.ip6.arpa: empty.db
  0.0.c.f.ip6.arpa: empty.db
  0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.8.e.f.ip6.arpa: empty.db

  archive.ubuntu.com: apt-mirror.ubuntu.db
  ports.ubuntu.com: apt-mirror.ubuntu.db
  security.ubuntu.com: apt-mirror.ubuntu.db
  ftp.debian.org: apt-mirror.db
  deb.debian.org: apt-mirror.db
  ftp.us.debian.org: apt-mirror.db
  deb.us.debian.org: apt-mirror.db

resolvers:
  - zone: .
    max-connections: 100
    cache-size: 20480
    nameservers:
      - proto: tcp-tls
        server-name: dns.google
        addr: "8.8.8.8:853"
      - proto: tcp-tls
        server-name: dns.google
        addr: "8.8.4.4:853"
    allow-only-from-private: true
    cache-max-time: 3600s
    cache-no-reply-time: 60s

localizers:
  - zone: gateway.foxden.network
    subnets:
    - 0.0.0.1/16
  - zone: dns.foxden.network
    subnets:
    - 0.0.0.53/16
  - zone: ntp.foxden.network
    subnets:
    - 0.0.0.123/16
  - zone: vpn.foxden.network
    subnets:
    - 0.0.1.1/16
  - zone: router.foxden.network
    subnets:
    - 0.0.1.1/16
  - zone: router-backup.foxden.network
    subnets:
    - 0.0.1.3/16
